services: 
  db:
    image: postgres:16
    container_name: db # local docker DNS name for postgres service
    env_file:
      - ../env/.env.docker
    ports: 
      - "${PG_PORT}:5432" # mapping - mycomputer:container port 
    volumes:
      - db_data:/var/lib/postgresql/data # data stays here even if container is removed
      - ../../db/migrations:/docker-entrypoint-initdb.d:ro # .. goes back to root of project, then db/migrations, mounts to /docker-entrypoint-initdb.d in container, read-only
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer: # separate adminer service from adminer:4 image - database UI at localhost:8080
    image: adminer:4
    container_name: adminer
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT}:8080"
    restart: always

volumes:
  db_data: