services: 
  db:
    image: postgres:16
    container_name: db
    env_file:
      - ../env/.env.docker
    ports: 
      - "${PG_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../../db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:4
    container_name: adminer
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT}:8080"
    restart: always

volumes:
  db_data: